openapi: 3.0.0
info:
  title: Games API
  version: 1.0.0
paths:
  /games:
    post:
      summary: ゲームを登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                creatorName:
                  type: string
                  description: ブース展示者名
                  example: "展示者名"
                organization:
                  type: string
                  description: 所属団体
                twitterId:
                  type: string
                  description: Twitter ID
                websiteUrl:
                  type: string
                  description: Webサイト等のURL
                title:
                  type: string
                  description: 展示するゲームタイトル
                  example: "ゲームタイトル"
                genre:
                  type: string
                  description: 展示するゲームのジャンル
                developmentEnvironment:
                  type: string
                  description: ゲームの開発環境
                description:
                  type: string
                  description: ゲームの説明
              required:
                - creatorName
                - title
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: ゲームの画像
      responses:
        '201':
          description: 成功 - ゲーム登録
          content:
            application/json:
              schema:
                type: object
                properties:
                  exhibitId:
                    type: string
                    description: 作品の一意識別子
        '400':
          description: Bad Request
        '404':
          description: Not Found
          
  /games/{gameId}:
    patch:
      summary: ゲーム情報を変更
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
            description: ゲームID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: ゲームの画像
      responses:
        '200':
          description: 成功 - ゲーム情報更新
          content:
            application/json:
              schema:
                type: object
                properties:
                  exhibitId:
                    type: string
                    description: 作品の一意識別子
        '204':
          description: No Content - 変更されました
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '404':
          description: Not Found
          
    get:
      summary: ゲーム情報を取得
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
            description: ゲームID
      responses:
        '200':
          description: 成功 - ゲーム情報取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  game:
                    type: object
                    properties:
                      gameId:
                        type: string
                      creatorName:
                        type: string
                      organization:
                        type: string
                      twitterId:
                        type: string
                      websiteUrl:
                        type: string
                      gameTitle:
                        type: string
                      gameGenre:
                        type: string
                      developmentEnvironment:
                        type: string
                      gameDescription:
                        type: string
                      term:
                        type: string
                      eventId:
                        type: string
                      discordUserId:
                        type: string
                      gameImageId:
                        type: string
        '404':
          description: Not Found
  /games/{gameId}/image:
    get:
      summary: ゲームの画像を取得
      parameters:
        - in: path
          name: gameId
          required: true
          schema:
            type: string
            description: ゲームID
      responses:
        '200':
          description: 成功 - ゲームの画像を取得
          content:
            image/png:
              schema:
                type: string
                format: binary
        '404':
          description: Not Found
  
  /events:
    post:
      summary: イベントを登録
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                slug:
                  type: string
                  description: URL
                title:
                  type: string
                  description: "第18回"
                gameSubmissionPeriodStart:
                  type: string
                  description: ゲーム展示の募集期間
                gameSubmissionPeriodEnd:
                  type: string
                  description: ゲーム展示の募集期間
              required:
                - slug
                - title
                - gameSubmissionPeriodStart
                - gameSubmissionPeriodEnd
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: イベントの画像
      responses:
        '201':
          description: 成功 - イベント登録
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventId:
                    type: string
                    description: イベントID
        '400':
          description: Bad Request
        '404':
          description: Not Found
    get:
      summary: イベントのリストを取得
      responses:
        '200':
          description: 成功 - イベントリスト取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      type: object
                      properties:
                        eventId:
                          type: string
                        slug:
                          type: string
                        title:
                          type: string
                        gameSubmissionPeriodStart:
                          type: string
                        gameSubmissionPeriodEnd:
                          type: string
        '404':
          description: Not Found
  /events/now:
    get:
      summary: 開催中のイベントを取得
      responses:
        '200':
          description: 成功 - 開催中のイベント取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventId:
                    type: string
                    description: イベントID
        '404':
          description: Not Found
  /events/{eventId}:
    patch:
      summary: イベントの情報を変更
      parameters:
        - in: path
          name: eventId
          required: true
          schema:
            type: string
            description: イベントID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: イベントの画像
      responses:
        '204':
          description: No Content - 変更されました
        '400':
          description: Bad Request
        '403':
          description: Forbidden
        '404':
          description: Not Found
    get:
      summary: イベントの情報を取得
      parameters:
        - in: path
          name: eventId
          required: true
          schema:
            type: string
            description: イベントID
      responses:
        '200':
          description: 成功 - イベント情報取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    type: object
                    properties:
                      eventId:
                        type: string
                      slug:
                        type: string
                      title:
                        type: string
                      gameSubmissionPeriodStart:
                        type: string
                      gameSubmissionPeriodEnd:
                        type: string
        '404':
          description: Not Found
  /events/{eventId}/image:
    get:
      summary: イベントの画像を取得
      parameters:
        - in: path
          name: eventId
          required: true
          schema:
            type: string
            description: イベントID
      responses:
        '200':
          description: 成功 - イベント画像取得
          content:
            image/png:
              schema:
                type: string
                format: binary
        '404':
          description: Not Found
  /events/{eventId}/games:
    get:
      summary: イベントに登録されているゲームのリストを取得
      parameters:
        - in: path
          name: eventId
          required: true
          schema:
            type: string
            description: イベントID
      responses:
        '200':
          description: 成功 - イベントに登録されているゲームのリスト取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  eventId:
                    type: string
                  games:
                    type: array
                    items:
                      type: object
                      properties:
                        gameId:
                          type: string
                        gameTitle:
                          type: string
                        creatorName:
                          type: string
                        gameDescription:
                          type: string
                        term:
                          type: string
        '404':
          description: Not Found
  /events/{eventId}/csv:
    get:
      summary: イベントとイベントに登録されているゲームの情報をCSV形式で取得
      parameters:
        - in: path
          name: eventId
          required: true
          schema:
            type: string
            description: イベントID
      responses:
        '200':
          description: 成功 - CSV形式で情報取得
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '404':
          description: Not Found
  
  /auth/login:
    post:
      summary: ログイン
      description: Discord OAuthを使ったログイン。
      responses:
        '204':
          description: No Content - ログインしました。
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /auth/logout:
    post:
      summary: ログアウト
      responses:
        '204':
          description: No Content - ログアウトしました。
          
  /users/me:
    get:
      summary: 自分のユーザー情報を取得
      responses:
        '200':
          description: 成功 - ユーザー情報取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      userId:
                        type: string
                      username:
                        type: string
                      profileImageUrl:
                        type: string
                      role:
                        type: string
        '404':
          description: Not Found
  /users/me/games:
    get:
      summary: 自分が登録したゲームのリストを取得
      responses:
        '200':
          description: 成功 - 登録ゲームリスト取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      $ref: '#/components/schemas/Game'
        '404':
          description: Not Found
  /users/{userId}:
    get:
      summary: ユーザー情報を取得
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功 - ユーザー情報取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      userId:
                        type: string
                      username:
                        type: string
                      profileImageUrl:
                        type: string
                      role:
                        type: string
        '404':
          description: Not Found
  /users/{userId}/games:
    get:
      summary: ユーザーが登録したゲームのリストを取得
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 成功 - 登録ゲームリスト取得
          content:
            application/json:
              schema:
                type: object
                properties:
                  games:
                    type: array
                    items:
                      $ref: '#/components/schemas/Game'
        '404':
          description: Not Found

  /contacts:
    post:
      summary: コンタクト用メールを送信
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 名前
                email:
                  type: string
                  description: メールアドレス
                message:
                  type: string
                  description: お問い合わせ内容
              required:
                - name
                - email
                - message
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request

components:
  schemas:
    Game:
      type: object
      properties:
        gameId:
          type: string
          description: ゲームID
        creatorName:
          type: string
          description: ブース展示者名
        organization:
          type: string
          description: 所属団体
        twitterId:
          type: string
          description: Twitter ID
        websiteUrl:
          type: string
          description: Webサイト等のURL
        gameTitle:
          type: string
          description: 展示するゲームタイトル
        gameGenre:
          type: string
          description: 展示するゲームのジャンル
        developmentEnvironment:
          type: string
          description: ゲームの開発環境
        gameDescription:
          type: string
          description: ゲームの説明
        term:
          type: string
          description: 用語
        eventId:
          type: string
          description: イベントID
        discordUserId:
          type: string
          description: DiscordのユーザーID
      required:
        - gameId
        - creatorName
        - gameTitle
        
    Event:
      type: object
      properties:
        eventId:
          type: string
          description: イベントID
        slug:
          type: string
          description: イベントのURL
        title:
          type: string
          description: "イベントのタイトル (例: 第18回)"
        gameSubmissionPeriodStart:
          type: string
          description: ゲーム展示の募集開始期間
        gameSubmissionPeriodEnd:
          type: string
          description: ゲーム展示の募集終了期間
      required:
        - eventId
        - slug
        - title
        - gameSubmissionPeriodStart
        - gameSubmissionPeriodEnd